name: delegated-execution-authority

plugins:
  - solidity:
    version: 0.8.14
  - name: foundry
    version: 0.8.9

vyper:
  version: 0.4.3

networks:
  custom:
    - name: hoodi
      chain_id: 560048
      ecosystem: ethereum

node:
  ethereum:
    hoodi:
      http_uri: ${HOODI_RPC_URI}

etherscan:
  ethereum:
    hoodi:
      uri: https://hoodi.etherscan.io
      api_uri: https://api-hoodi.etherscan.io/api
